### ISSUE TITLE
Transcation need to be highligh to be seen

### ISSUE THREAD

**Issue by feydreva** [sparkspay/sparks#11]
### Describe the issue
Lots of graphical bug
 In Transaction menu, could not see transaction expect with you highlight it
In main windows, the top menu is not visible 

#### If so, please list the steps to reproduce below:
1. Open SparkPay
2.Go transaction
3.

### Expected behavior
I want to see transaction, not have to click on each of them to see them

### Screenshots.
Transaction menu
![image](https://user-images.githubusercontent.com/3083670/175163643-59f99ea1-f867-43b9-b599-8842e7db0586.png)
Main menu
![image](https://user-images.githubusercontent.com/3083670/175164033-772d4d5d-f53d-4f39-9713-11f4a75c75e1.png)

### What version of Sparks Core are you using?
v0.13.4.0-3643eebf4

### Machine specs:
- OS: Arch
- CPU: i5 7700k
- RAM: 16
- Disk size: 2Tb
- Disk Type (HD/SDD): ssd

**Comment by Dilusha-M** [comment]
apology for late reply. UI have been fixed with recent major updates. let us know if you still has the issue.
