### ISSUE TITLE
Depends issue

### ISSUE THREAD

**Issue by bogtroll** [sparkspay/sparks#50]
Compiling depends fails when it tries to download from: https://github.com/Sparkspay/bls-signatures/archive which looking at the repo doesn't exist.

**Comment by Dilusha-M** [comment]
@bogtroll typo error. could you try with : https://github.com/dashpay/bls-signatures

**Comment by bogtroll** [comment]
Thanks for getting back to me but that still doesn't work as it's looking for "bls-sparks" whic of course DASH github doesn't have.  I've messed with the file name to try and get what's needed from dash but it's v1.3.1 rather than 1.2.0 that SPARKS wants and the checksums don't match so it won't compile it.  Please can the necessary file be added to the sparks github?
Thanks.

**Comment by Dilusha-M** [comment]
@bogtroll , fix has been pushed to 'develop' branch (tested and worked for with a fresh clone of repository).

**Comment by bogtroll** [comment]
@Dilusha-M Thank you.  That compiled no problem.  I've updated our wallets and it can be taken out of maint. once they've synced from zero as the block indexes were trashed.
